name: Build SunamoLaTeX

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoLaTeX
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoLaTeX/SunamoLaTeX.csproj

    - name: Build
      run: dotnet build SunamoLaTeX/SunamoLaTeX.csproj --configuration Release --no-restore

  test:
    name: Test SunamoLaTeX.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoLaTeX.Tests/SunamoLaTeX.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoLaTeX.Tests/SunamoLaTeX.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoLaTeX.Tests/SunamoLaTeX.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
